server:
  port: 8899
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 100MB

spring:
  application:
    name: springmvc-demo

shenyu:
  register:
    registerType: http
    serverLists: http://localhost:9095
    props:
      username: admin
      password: 123456
  client:
    http:
      props:
        contextPath: /springdemo
        appName: springmvc-demo